echo "Test1 : How are you"
echo "test2 : I am good"
echo "tech1 :: all going good sofar"
echo "This is updated with vscode from local machine"
echo " this is updated on 10th june"
echo "test this update"
